### ISSUE TITLE
2.0 버전 Todo List

### ISSUE THREAD

**Issue by KimTaeHyeong17** [ProjectInTheClass/Wa-ha#80]
- [ ] RxSwift 적용 MVC -> MVVM 구조 개선
- [ ] 이미지 프로세싱 성능 개선
- [ ] 각종 버그 수정
- [ ] 사용하지 않는 코드 정리
- [ ] SwiftLint 적용
- [ ] 시간제약 없이 실시간 렌더링 ram 말로 device에 저장하는 방법
